ALTER TABLE "topics"
ADD COLUMN "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "difficulty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "topics"
ALTER COLUMN "updated_at" DROP DEFAULT;
